api_host: us-0120.octarinesec.com
api_port: 443
config_version: 0.12.0
embedded_ip: true
long_lived: false
restful_report: false
service_version: "1.0"
use_octarine_encryption: true
use_quotas: "true"
version_tag: 0.12.0
